# Use the official Ubuntu 22.04 image as a base
FROM ubuntu:22.04

# Update the system and install any necessary packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get install build-essential autoconf automake libpcre3-dev libevent-dev pkg-config zlib1g-dev libssl-dev
RUN apt install -y vim git
